# -*- coding: utf-8 -*-
"""Copy of Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YRnqb0ze2bYyDVnk9ogt2qaPRVTwvcTf
"""

# Input tow varibel xand y and find X in to the power of Y
x = int(input('Enter the value of X:'))
y = int(input('Enter the value of Y:'))

# X in to the power of Y = Z
z = pow(x,y)
print('Z=',z)